name: Tauri CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js (pointing to dashboard directory)
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'dashboard/package-lock.json'  # or 'dashboard/yarn.lock'

    # Setup Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    # Install dependencies (in dashboard folder)
    - name: Install dependencies
      working-directory: ./dashboard
      run: npm install

    # Build steps (all in dashboard folder)
    # - name: Build frontend
    #   working-directory: ./dashboard
    #   run: npm run build

    - name: Build Tauri
      working-directory: ./dashboard
      run: npx tauri build

    # # Run tests
    # - name: Run tests
    #   working-directory: ./dashboard
    #   run: npm test
