name: Update Homebrew Formula

on:
  release:
    types: [published]
    
permissions:
  contents: write  # Required to push to the repository
jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v4
        with:
          repository: EasyCanadianGamer/homebrew-projexnexa
          token: ${{ secrets.GITHUB_TOKEN}}
          path: homebrew-tap
 
      - name: Get .app.tar.gz Info
        id: release
        run: |
          ASSET_URL=$(curl -s https://api.github.com/repos/EasyCanadianGamer/ProjexNexa/releases/latest | 
                    jq -r '.assets[] | select(.name | endswith("app.tar.gz")) | .browser_download_url')
          SHA=$(curl -sL "$ASSET_URL" | sha256sum | cut -d ' ' -f 1)
          echo "url=${ASSET_URL}" >> $GITHUB_OUTPUT
          echo "sha256=${SHA}" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          cd homebrew-tap
          cat > Formula/projexnexa.rb << EOF
          class ProjexNexa < Formula
            desc "Tauri application for project management"
            homepage "https://github.com/EasyCanadianGamer/ProjexNexa"
            url "${{ steps.release.outputs.url }}"
            sha256 "${{ steps.release.outputs.sha256 }}"
            license "MIT"

            depends_on macos: :monterey

            def install
              prefix.install "ProjexNexa.app"
              bin.write_exec_script prefix/"ProjexNexa.app/Contents/MacOS/ProjexNexa"
            end

            test do
              system "#{bin}/ProjexNexa", "--version"
            end
          end
          EOF

      - name: Commit and Push
        run: |
          cd homebrew-tap
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/projexnexa.rb
          git commit -m "Update projexnexa to ${{ github.event.release.tag_name }}"
          git push
