name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homebrew Tap
        uses: actions/checkout@v4
        with:
          repository: EasyCanadianGamer/homebrew-projexnexa
          token: ${{ secrets.PAT_TOKEN }}
          path: homebrew-tap
          fetch-depth: 0  # Required for proper git history

      - name: Get Release Info
        id: release
        run: |
          ASSET_URL=$(curl -sLH "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/EasyCanadianGamer/ProjexNexa/releases/latest" \
            | jq -r '.assets[] | select(.name | endswith("app.tar.gz")) | .browser_download_url')
          SHA=$(curl -sL "$ASSET_URL" | sha256sum | cut -d ' ' -f 1)
          echo "url=${ASSET_URL}" >> $GITHUB_OUTPUT
          echo "sha256=${SHA}" >> $GITHUB_OUTPUT

      - name: Update Formula
        run: |
          cd homebrew-tap
          cat > Formula/projexnexa.rb << 'EOF'
          class Projexnexa < Formula
            desc "Tauri application for project management"
            homepage "https://github.com/EasyCanadianGamer/ProjexNexa"
            url "${{ steps.release.outputs.url }}"
            sha256 "${{ steps.release.outputs.sha256 }}"
            license "MIT"

            depends_on macos: :monterey

            def install
              # 1. Get exact downloaded path
              tarball = cached_download
              ohai "Using tarball at: #{tarball}"
              
              # 2. Create extraction directory
              temp_dir = buildpath/"temp_extract"
              temp_dir.mkpath
              
              # 3. Extract with full path output
              system "tar", "-xzvf", tarball, "-C", temp_dir, "--strip-components", "0"
              
              # 4. Verify extraction
              extracted = Dir.glob(temp_dir/"ProjexNexa.app")
              odie "App bundle not found in #{temp_dir}" if extracted.empty?
              
              # 5. Install to Homebrew prefix
              prefix.install extracted.first => "ProjexNexa.app"
              
              # 6. Create launcher script
              bin.write_exec_script prefix/"ProjexNexa.app/Contents/MacOS/ProjexNexa"
            end

            test do
              system "#{bin}/ProjexNexa", "--version"
            end
          end
          EOF

      - name: Commit and Push Changes
        run: |
          cd homebrew-tap
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/projexnexa.rb
          git commit -m "Update projexnexa to ${{ github.event.release.tag_name }} [skip ci]"
          git push "https://${{ secrets.PAT_TOKEN }}@github.com/EasyCanadianGamer/homebrew-projexnexa.git" HEAD:main
